name: smart_travel_advisor
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^3.0.1
  cupertino_icons: ^1.0.2
  google_maps_flutter: ^2.2.1
  flutter_rating_stars: ^1.0.3+4
  firebase_auth: ^4.1.3
  firebase_core: ^2.3.0
  cloud_firestore: ^4.1.0
  provider: ^6.0.4
  google_sign_in: ^5.4.2
  dropdown_button2: ^1.9.1
  location: ^4.4.0
  rename: ^2.0.1
  device_preview: ^1.1.0
  share: ^2.0.4
  dialog_flowtter: ^0.3.3
  firebase_storage: ^11.0.5
  image_picker: ^0.8.6
  intl: ^0.17.0
  flutter_login_facebook: ^1.6.2
  flutter_slidable: ^2.0.0


dev_dependencies:
  flutter_launcher_icons: "^0.11.0"
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon.png"

  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/appLogo/
    - assets/images/
    - assets/
    - assets/finalTrips/
  #   - images/a_dot_ham.jpeg
